name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        type: string
        description: 'Semver (eg: v1.2.3 or v1.2.3-rc.1)'
        required: true

jobs:
  release:
    if: github.triggering_actor == 'jerethom'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        run: |
          git config --global user.name '${{ github.triggering_actor }}'
          git config --global user.email "${{ github.triggering_actor}}@users.noreply.github.com"

          git add .
          git commit --allow-empty -m 'bump ${{ inputs.semver }}'
          git tag ${{ inputs.semver }}
          git push origin ${{ inputs.semver }}

      - name: Generate changelog
        run: |
          curl https://github.com/gookit/gitw/releases/latest/download/chlog-linux-amd64 -L -o /usr/local/bin/chlog
          chmod a+x /usr/local/bin/chlog
          chlog -c .github/changelog.yml -o changelog.md prev last 

      - name: Check if pre-release
        id: check_prerelease
        run: |
          if [[ ${{ inputs.semver }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+-.*$ ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ inputs.semver }}
          tag_name: ${{ inputs.semver }}
          body_path: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}
